version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/uniform_management
      - PORT=3000
    depends_on:
      - mongo
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: always

  mongo:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data: 